
name: worldroll
services:
  node:
    image: "node"
    container_name: worldtower
    working_dir: /app
    ports:
      - "8555:8555"
    command: sh -c "npm i && npm run build && npm start"
    volumes:
      - /var/www/worldroll:/app
    networks:
      - ows
    extra_hosts:
      - "host.docker.internal:65.21.140.157"
      
networks:
  ows:
    external: true
